spring.application.name=smart-academic-lab
spring.datasource.url=jdbc:mysql://localhost:3306/academiclab
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=false
#spring.h2.console.enabled=true
#spring.thymeleaf.cache=false
#app.cancel-before-hours=24

#hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.signer-key=307bae87b4da59e5d373eeb6858d548866a0fe041b8db89d084a1ba18ad24951
